import React from 'react'
import './energy.css'

const Energy = () => {
	return (
		<div className='energy'>
			<p className="title">Energy Potential</p>
      <p className="content">
        Namazu also identifies regions on Mars where seismic activity is frequent enough to generate energy. By removing noise from the seismic data, the app reveals zones that could potentially support energy plants that harness the energy generated by Marsquakes. This helps future colonists plan energy infrastructure in the most suitable locations on the planet.

        <h3>Benefits of the Data Structure Analysis</h3>
        <ul>
          <li>Improved Safety: Engineers can identify safe zones for construction, minimizing risks from seismic activity.</li>
          <li>Energy Opportunities: The app highlights areas where seismic energy could be harnessed, supporting sustainable energy solutions on Mars.</li>
          <li>Accurate Data: By filtering out noise, Namazu ensures that the seismic data is clear and reliable, making it easier to analyze and apply in real-world scenarios.</li>
        </ul>
      </p>
		</div>
	)
}

export default Energy